builds:
  -
    env:
      - CGO_ENABLED=0

    main: ./cmd/dirstalk/main.go

    goos:
      - freebsd
      - linux
      - darwin
      - openbsd

    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7

    ldflags:
      - -X github.com/stefanoj3/dirstalk/pkg/cmd.Version={{.Version}} -X github.com/stefanoj3/dirstalk/pkg/cmd.BuildTime={{.Timestamp}}

archive:
  replacements:
    darwin: Darwin
    linux: Linux
    openbsd: OpenBSD
    freebsd: FreeBSD
    android: Android
    386: i386
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
