sudo: required

os:
  - linux
  - osx

language: go

go:
  - 1.11.x
  - master

  matrix:
    # It's ok if our code fails on unstable development versions of Go.
    allow_failures:
    - go: master
    # Don't wait for tip tests to finish. Mark the test run green if the
    # tests pass on the stable versions of Go.
    fast_finish: true
    include:
      - os: linux
        go: "1.11.x"
        sudo: true
        cache:
          directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod

      - os: osx
        go: "1.11.x"
        cache:
          directories:
          - $HOME/Library/Caches/go-build
          - $HOME/gopath/pkg/mod


install:
- make dep

script:
- make check
- make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
